const ADD_FLOOR = 'ADD_FLOOR'
const ADD_ELEVATOR = 'ADD_ELEVATOR'
const TOGGLE_CALL = 'TOGGLE_CALL'
const TOGGLE_ANSWER = 'TOGGLE_ANSWER'
const SET_FLOOR_STATUS = 'SET_FLOOR_STATUS'
const SET_ELEVATOR_STATUS = 'SET_ELEVATOR_STATUS'
const SET_ELEVATOR_POSITION = 'SET_ELEVATOR_POSITION'
const ELEVATORS_COUNT = 1;
const FLOORS_COUNT = 10;

const ELEVATOR_STATUS = {
  MOVING: 'MOVING',
  STAYING: 'STAYING',
  FREE: 'FREE'
}

export {
  ADD_FLOOR,
  ADD_ELEVATOR,
  TOGGLE_CALL,
  TOGGLE_ANSWER,
  SET_FLOOR_STATUS,
  SET_ELEVATOR_STATUS,
  SET_ELEVATOR_POSITION,
  ELEVATOR_STATUS,
  ELEVATORS_COUNT,
  FLOORS_COUNT,
}